package edu.fcse.domcolorclassifier.gui;

import javax.swing.JFileChooser;

/**
 * Form the sets up the parameters for the classifier and the input data set
 * location.
 *
 * @author Blagoj Atanasovski
 */
public class InitFrame extends javax.swing.JFrame {

    /**
     * Creates new form InitFrame
     */
    public InitFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorSpaceButtonGroup = new javax.swing.ButtonGroup();
        weightFunctionButtonGroup = new javax.swing.ButtonGroup();
        smoothingFunctionbuttonGroup = new javax.swing.ButtonGroup();
        chosenInitFolderTextField = new javax.swing.JTextField();
        cChooseInitFolderButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        csRGBRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        csLabRadioButton = new javax.swing.JRadioButton();
        csLuvRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        wfNoneRadioButton = new javax.swing.JRadioButton();
        wfReciRadioButton = new javax.swing.JRadioButton();
        wfExpRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        sfNoneRadioButton = new javax.swing.JRadioButton();
        sfAVGRadioButton = new javax.swing.JRadioButton();
        sfMINRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        algorithmComboBox = new javax.swing.JComboBox();
        useDiscardDistanceCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        discardDistanceTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        maxDiscardDistanceLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        useFixedValCheckBox = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        autoStartCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DomColorClassification - Init");

        cChooseInitFolderButton.setText("Browse");
        cChooseInitFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cChooseInitFolderButtonActionPerformed(evt);
            }
        });

        jLabel1.setLabelFor(cChooseInitFolderButton);
        jLabel1.setText("Choose the forlder with the images:");

        colorSpaceButtonGroup.add(csRGBRadioButton);
        csRGBRadioButton.setSelected(true);
        csRGBRadioButton.setText("RGB");

        jLabel2.setLabelFor(csRGBRadioButton);
        jLabel2.setText("Color Space:");

        colorSpaceButtonGroup.add(csLabRadioButton);
        csLabRadioButton.setText("Lab");
        csLabRadioButton.setEnabled(false);

        colorSpaceButtonGroup.add(csLuvRadioButton);
        csLuvRadioButton.setText("Luv");
        csLuvRadioButton.setEnabled(false);

        jLabel3.setText("Weight Function:");

        weightFunctionButtonGroup.add(wfNoneRadioButton);
        wfNoneRadioButton.setText("None");

        weightFunctionButtonGroup.add(wfReciRadioButton);
        wfReciRadioButton.setSelected(true);
        wfReciRadioButton.setText("Reciprocal");

        weightFunctionButtonGroup.add(wfExpRadioButton);
        wfExpRadioButton.setText("Exponential");

        jLabel4.setText("Smoothing Function");

        smoothingFunctionbuttonGroup.add(sfNoneRadioButton);
        sfNoneRadioButton.setSelected(true);
        sfNoneRadioButton.setText("None");

        smoothingFunctionbuttonGroup.add(sfAVGRadioButton);
        sfAVGRadioButton.setText("AVG");

        smoothingFunctionbuttonGroup.add(sfMINRadioButton);
        sfMINRadioButton.setText("MIN");

        jLabel5.setLabelFor(algorithmComboBox);
        jLabel5.setText("Algorithm");

        algorithmComboBox.setMaximumRowCount(5);
        algorithmComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Algorithm", "Equal Distance Count Double", "Add To Multiple Centers" }));
        algorithmComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algorithmComboBoxActionPerformed(evt);
            }
        });

        useDiscardDistanceCheckBox.setText("Use discard distance");

        jLabel6.setText("Distance:");

        jLabel7.setText("from maximum");

        maxDiscardDistanceLabel.setText("440");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        useFixedValCheckBox.setText("Use fixed value addition");

        jButton2.setText("Classify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        autoStartCheckBox.setText("Start automaticly");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cChooseInitFolderButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chosenInitFolderTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sfNoneRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(sfAVGRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(sfMINRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(csRGBRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(csLabRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(csLuvRadioButton))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(wfNoneRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(wfReciRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(wfExpRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(algorithmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(useDiscardDistanceCheckBox)
                                    .addComponent(useFixedValCheckBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(discardDistanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(maxDiscardDistanceLabel))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(autoStartCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cChooseInitFolderButton)
                    .addComponent(chosenInitFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(csRGBRadioButton)
                            .addComponent(csLabRadioButton)
                            .addComponent(csLuvRadioButton)
                            .addComponent(wfNoneRadioButton)
                            .addComponent(wfReciRadioButton)
                            .addComponent(wfExpRadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(algorithmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sfNoneRadioButton)
                                .addComponent(sfAVGRadioButton)
                                .addComponent(sfMINRadioButton))
                            .addComponent(useDiscardDistanceCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(discardDistanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(maxDiscardDistanceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(useFixedValCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(autoStartCheckBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cChooseInitFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cChooseInitFolderButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            chosenInitFolderTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
            
        }
    }//GEN-LAST:event_cChooseInitFolderButtonActionPerformed
    
    private void algorithmComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algorithmComboBoxActionPerformed
        String selection = (String) algorithmComboBox.getSelectedItem();
        //Basic Algorithm, Equal Distance Count Double, Add To Multiple Centers
        if (selection.equals("Basic Algorithm")) {
            
            useFixedValCheckBox.setEnabled(true);
        } else if (selection.equals("Equal Distance Count Double")) {
            useFixedValCheckBox.setEnabled(true);
        } else {
            useFixedValCheckBox.setEnabled(false);
        }
    }//GEN-LAST:event_algorithmComboBoxActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ClassificationFrame cf = new ClassificationFrame();
        cf.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox algorithmComboBox;
    private javax.swing.JCheckBox autoStartCheckBox;
    private javax.swing.JButton cChooseInitFolderButton;
    private javax.swing.JTextField chosenInitFolderTextField;
    private javax.swing.ButtonGroup colorSpaceButtonGroup;
    private javax.swing.JRadioButton csLabRadioButton;
    private javax.swing.JRadioButton csLuvRadioButton;
    private javax.swing.JRadioButton csRGBRadioButton;
    private javax.swing.JTextField discardDistanceTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel maxDiscardDistanceLabel;
    private javax.swing.JRadioButton sfAVGRadioButton;
    private javax.swing.JRadioButton sfMINRadioButton;
    private javax.swing.JRadioButton sfNoneRadioButton;
    private javax.swing.ButtonGroup smoothingFunctionbuttonGroup;
    private javax.swing.JCheckBox useDiscardDistanceCheckBox;
    private javax.swing.JCheckBox useFixedValCheckBox;
    private javax.swing.ButtonGroup weightFunctionButtonGroup;
    private javax.swing.JRadioButton wfExpRadioButton;
    private javax.swing.JRadioButton wfNoneRadioButton;
    private javax.swing.JRadioButton wfReciRadioButton;
    // End of variables declaration//GEN-END:variables
}
